module.exports = {
    extends: ["stylelint-config-prettier"],
    plugins: ["stylelint-order"],
    rules: {
      "order/order": [
        "custom-properties",
        "dollar-variables",
        {
          type: "at-rule",
          name: "extend"
        },
        "declarations",
        {
          type: "at-rule",
          name: "include",
          hasBlock: false
        },
        {
          type: "at-rule",
          name: "include",
          hasBlock: true
        },
        "rules"
      ],
      "order/properties-order": [
        
 
        "display",
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "float",
        "clear",
        "overflow",
        "overflow-x",
        "overflow-y",
        "clip",
        "box-sizing",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "border",
        "border-spacing",
        "border-collapse",
        "border-width",
        "border-style",
        "border-color",
        "border-top",
        "border-top-width",
        "border-top-style",
        "border-top-color",
        "border-right",
        "border-right-width",
        "border-right-style",
        "border-right-color",
        "border-bottom",
        "border-bottom-width",
        "border-bottom-style",
        "border-bottom-color",
        "border-left",
        "border-left-width",
        "border-left-style",
        "border-left-color",
        "border-radius",
        "border-image",
        "border-image-source",
        "border-image-slice",
        "border-image-width",
        "border-image-outset",
        "border-image-repeat",
 
        "font",
        "font-family",
        "font-size",
        "font-weight",
        "font-style",
        "font-variant",
        "font-size-adjust",
        "font-stretch",
        "font-effect",
        "font-emphasize",
        "font-emphasize-position",
        "font-emphasize-style",
        "font-smooth",
        "line-height",
        "color",
        "text-align",
        "text-align-last",
        "text-emphasis",
        "text-emphasis-color",
        "text-emphasis-style",
        "text-emphasis-position",
        "text-decoration",
        "text-indent",
        "text-justify",
        "text-outline",
        "text-transform",
        "text-wrap",
        "text-overflow",
        "text-overflow-ellipsis",
        "text-overflow-mode",
        "text-shadow",
        "white-space",
        "word-wrap",
        "word-break",
        "tab-size",
        "hyphens",
        "letter-spacing",

        "background",
        "background-color",
        "background-image",
        "background-repeat",
        "background-position",
        "background-position-x",
        "background-position-y",
        "background-size",
        "background-clip",
        "background-origin",
        "background-attachment",
        "opacity",
        "filter",
        "transform",
        "transform-origin",
        "visibility",
        "cursor",
        "backface-visibility",
        "box-shadow",
        "outline",
        "outline-width",
        "outline-style",
        "outline-color",
        "outline-offset",
        "z-index",
        "transition",
        "transition-delay",
        "transition-timing-function",
        "transition-duration",
        "transition-property",
        "animation",
        "animation-name",
        "animation-duration",
        "animation-play-state",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-direction",
        "vertical-align",
        "list-style",
        "list-style-position",
        "list-style-type",
        "list-style-image",
        "pointer-events",
        "resize",
        "user-select"
      ]
    ,
      "rule-empty-line-before": [
        "always-multi-line",
        {
          except: ["first-nested"],
          ignore: ["after-comment"]
        }
      ],
      "declaration-empty-line-before": [
        "never",
        {
          ignore: ["after-declaration", "first-nested"]
        }
      ],
      "at-rule-empty-line-before": [
        "always",
        {
          ignoreAtRules: ["else"],
          ignore: ["after-comment"],
          except: ["first-nested", "blockless-after-blockless"]
        }
      ]
    }
  };